In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Libraries loaded successfully!")

Libraries loaded successfully!

In [2]:
df = pd.read_csv("../data/raw/APY.csv")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 345336
Columns: 8

In [3]:
df.head()

,State,District,Crop,Crop_Year,Season,Area,Production,Yield
0,Andaman and Nicobar Island,NICOBARS,Arecanut,2007,Kharif,2439.6,3415.0,1.40
1,Andaman and Nicobar Island,NICOBARS,Arecanut,2007,Rabi,1626.4,2277.0,1.40
2,Andaman and Nicobar Island,NICOBARS,Arecanut,2008,Autumn,4147.0,3060.0,0.74
3,Andaman and Nicobar Island,NICOBARS,Arecanut,2008,Summer,4147.0,2660.0,0.64
4,Andaman and Nicobar Island,NICOBARS,Arecanut,2009,Autumn,4153.0,3120.0,0.75

In [4]:
print(df.columns.tolist())

['State', 'District ', 'Crop', 'Crop_Year', 'Season', 'Area ', 'Production', 'Yield']

In [5]:
df.columns = df.columns.str.strip()

print(df.columns.tolist())

['State', 'District', 'Crop', 'Crop_Year', 'Season', 'Area', 'Production', 'Yield']

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 345336 entries, 0 to 345335
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   State       345336 non-null  str
 1   District    345336 non-null  str
 2   Crop        345327 non-null  str
 3   Crop_Year   345336 non-null  int64
 4   Season      345336 non-null  str
 5   Area        345336 non-null  float64
 6   Production  340388 non-null  float64
 7   Yield       345336 non-null  float64
dtypes: float64(3), int64(1), str(4)
memory usage: 21.1 MB

In [7]:
missing = df.isnull().sum()

print(missing[missing > 0])

Crop             9
Production    4948
dtype: int64

In [8]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [9]:
print("Number of states:", df["State"].nunique())

print("\nStates:")
print(sorted(df["State"].dropna().unique()))

Number of states: 37

States:
['Andaman and Nicobar Island', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'CHANDIGARH', 'Chhattisgarh', 'Dadra and Nagar Haveli', 'Daman and Diu', 'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Laddak', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'THE DADRA AND NAGAR HAVELI', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']

In [10]:
print("Number of districts:", df["District"].nunique())

Number of districts: 707

In [11]:
print("Number of crops:", df["Crop"].nunique())

print("\nCrops:")
print(sorted(df["Crop"].dropna().unique()))

Number of crops: 55

Crops:
['Arecanut', 'Arhar/Tur', 'Bajra', 'Banana', 'Barley', 'Black pepper', 'Cardamom', 'Cashewnut', 'Castor seed', 'Coconut ', 'Coriander', 'Cotton(lint)', 'Cowpea(Lobia)', 'Dry chillies', 'Garlic', 'Ginger', 'Gram', 'Groundnut', 'Guar seed', 'Horse-gram', 'Jowar', 'Jute', 'Khesari', 'Linseed', 'Maize', 'Masoor', 'Mesta', 'Moong(Green Gram)', 'Moth', 'Niger seed', 'Oilseeds total', 'Onion', 'Other  Rabi pulses', 'Other Cereals', 'Other Kharif pulses', 'Other Summer Pulses', 'Peas & beans (Pulses)', 'Potato', 'Ragi', 'Rapeseed &Mustard', 'Rice', 'Safflower', 'Sannhamp', 'Sesamum', 'Small millets', 'Soyabean', 'Sugarcane', 'Sunflower', 'Sweet potato', 'Tapioca', 'Tobacco', 'Turmeric', 'Urad', 'Wheat', 'other oilseeds']

In [12]:
print("Minimum year:", df["Crop_Year"].min())
print("Maximum year:", df["Crop_Year"].max())

Minimum year: 1997
Maximum year: 2020

In [13]:
year_counts = df["Crop_Year"].value_counts().sort_index()

print(year_counts)

Crop_Year
1997     8548
1998    12289
1999    13011
2000    13588
2001    13305
2002    14178
2003    14660
2004    14149
2005    14062
2006    14675
2007    14680
2008    15149
2009    15339
2010    14888
2011    16126
2012    15278
2013    16178
2014    15586
2015    16339
2016    17416
2017    18008
2018    18301
2019    19264
2020      319
Name: count, dtype: int64

In [14]:
print(df["Season"].value_counts())

Season
Kharif         138369
Rabi           100951
Whole Year      68680
Summer          22098
Winter           8249
Autumn           6989
Name: count, dtype: int64

In [15]:
print("Negative Area:",
      (df["Area"] < 0).sum())

print("Negative Production:",
      (df["Production"] < 0).sum())

print("Negative Yield:",
      (df["Yield"] < 0).sum())

Negative Area: 0
Negative Production: 0
Negative Yield: 0

In [16]:
print("Area = 0:",
      (df["Area"] == 0).sum())

print("Production = 0:",
      (df["Production"] == 0).sum())

print("Yield = 0:",
      (df["Yield"] == 0).sum())

Area = 0: 0
Production = 0: 1466
Yield = 0: 6096

In [17]:
df["Yield"].describe()

count    345336.000000
mean         79.423135
std         916.678396
min           0.000000
25%           0.550000
50%           1.000000
75%           2.470000
max       43958.330000
Name: Yield, dtype: float64

In [18]:
df.sort_values(
    "Yield",
    ascending=False
)[
    ["State", "District", "Crop",
     "Crop_Year", "Area",
     "Production", "Yield"]
].head(20)

,State,District,Crop,Crop_Year,Area,Production,Yield
24551,Assam,TINSUKIA,Coconut,2018,72.0,3165000.0,43958.33
333525,West Bengal,BIRBHUM,Coconut,2006,509.0,19749200.0,38800.00
258896,Tamil Nadu,ERODE,Coconut,2008,10014.0,331800000.0,33133.61
24552,Assam,TINSUKIA,Coconut,2019,71.0,2340000.0,32957.75
3122,Andhra Pradesh,PRAKASAM,Coconut,2018,19.0,600000.0,31578.95
24548,Assam,TINSUKIA,Coconut,2015,75.0,2257000.0,30093.33
3229,Andhra Pradesh,WEST GODAVARI,Coconut,2019,23316.0,694164000.0,29772.00
24549,Assam,TINSUKIA,Coconut,2016,76.0,2188000.0,28789.47
24303,Assam,KAMRUP,Coconut,2005,2026.0,57405000.0,28334.16
24402,Assam,LAKHIMPUR,Coconut,2001,192.0,5044000.0,26270.83
259133,Tamil Nadu,THENI,Coconut,2005,15342.0,394900000.0,25739.80
24292,Assam,JORHAT,Coconut,2016,453.0,11520000.0,25430.46
259184,Tamil Nadu,TIRUCHIRAPPALLI,Coconut,2008,6703.0,165100000.0,24630.76
259107,Tamil Nadu,THANJAVUR,Coconut,2011,33742.0,823800000.0,24414.68
24236,Assam,GOLAGHAT,Coconut,2005,658.0,16062000.0,24410.33
3121,Andhra Pradesh,PRAKASAM,Coconut,2017,21.0,500000.0,23809.52
259167,Tamil Nadu,THIRUVARUR,Coconut,2007,5374.0,126300000.0,23502.05
258854,Tamil Nadu,CUDDALORE,Coconut,2016,1640.0,38100000.0,23231.71
258933,Tamil Nadu,KANNIYAKUMARI,Coconut,2014,24232.0,562500000.0,23213.11
258856,Tamil Nadu,CUDDALORE,Coconut,2018,1609.0,37100000.0,23057.80